version: "1.0"

services:
  nextjs-app:
    build: ./front-end
    container_name: mobile-shop
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://jsonserver.westore.site:4003 # Gọi tới service json-server
    depends_on:
      - json-server
  json-server:
    build: ./json-server
    container_name: json-server
    volumes:
      - ./json-server/db.json:/app/db.json
    ports:
      - "4003:4003"
    restart: always
